'use strict';

var SANS_SERIF = [
  '',
  '',
  '',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '',
  '',
  '',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  '        iiiiiiiiiii',
  ''
];

var MONO = [
  '            iiii',
  '          iiiiiiii',
  '         iiiiiiiiii',
  '          iiiiiiii',
  '           iiiiii',
  '             ii',
  '',
  '',
  '',
  '',
  '',
  'iiiiiiiiiiiiiiiiiii',
  'iiiiiiiiiiiiiiiiiii',
  'iiiiiiiiiiiiiiiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiiii',
  'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ''
];

var SERIF = [
  '',
  '',
  '           iiiiii',
  '          iiiiiiii',
  '         iiiiiiiiii',
  '          iiiiiiii',
  '            iiii',
  '',
  '',
  '',
  '',
  '',
  '        iiiiiiiiii',
  '    iiiiiiiiiiiiii',
  '       iiiiiiiiiii',
  '          iiiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '           iiiiiii',
  '          iiiiiiiii',
  '     iiiiiiiiiiiiiiiiiii',
  '     iiiiiiiiiiiiiiiiiii',
  ''
];

var SCRIPT = [
  '',
  '',
  '',
  '                           i',
  '                          ii',
  '                        iiii',
  '                      iiii',
  '                    iiiii',
  '                   iiii',
  '                  ii',
  '                 i',
  '',
  '',
  '                iiii',
  '             iiiiiiii',
  '           iiiiiiiiii',
  '         ii    iiiiii',
  '        ii     iiiiii',
  '       ii      iiiiii',
  '       i       iiiii',
  '              iiiiii',
  '              iiiiii',
  '              iiiii',
  '             iiiiii',
  '             iiiiii',
  '             iiiii',
  '             iiiii',
  '            iiiiii      i',
  '            iiiiii    ii',
  '            iiiiii  iii',
  '            iiiiiiiii',
  '            iiiiiii',
  '              ii'
];

module.exports = {SANS_SERIF, MONO, SERIF, SCRIPT};
